### ISSUE TITLE
Error in output code when using 6to5-loader with coreAliasing

### ISSUE THREAD

**Issue by roman01la** [6to5/6to5-loader#15]
I'm using `6to5-loader` with `coreAliasing` and getting the following error in browser's console:
```
Uncaught TypeError: Cannot read property 'TypeError' of undefined
```
It's referencing to `TypeError = _core.global.TypeError` inside of `core-js` module. `_core` object appears to be empty.

Try this [project](https://github.com/chicoxyzzy/real-world-react/tree/webpack) to reproduce error.

**Comment by sebmck** [comment]
As I said [here](https://github.com/6to5/6to5/issues/377#issuecomment-70340137), I need the **specific** code or actual steps to reproduce.

**Comment by roman01la** [comment]
@sebmck I'm sorry.
- Install **webpack**: `npm install -g webpack`
- Fetch [project](https://github.com/chicoxyzzy/real-world-react/tree/webpack)
- Run `npm install && webpack`
- Open `index.html` in the browser and pay attention to the console output

**Comment by sebmck** [comment]
It's a problem with the webpack config. On line 16 of [webpack.config.js](https://github.com/chicoxyzzy/real-world-react/blob/webpack/webpack.config.js#L16) it should be:

```javascript
{ test: /\.js$/, exclude: /node_modules/, loaders: ['6to5-loader?optional=coreAliasing'] }
```

as specified in the [README](https://github.com/6to5/6to5-loader#usage).

**Comment by roman01la** [comment]
@sebmck The only diff here is String vs RegExp in `exclude` option, but I'm not specifying it. Can you try just with `test` and `loaders`?

**Comment by sebmck** [comment]
@roman01la The different is that `node_modules` has a dash in it so 6to5 is being ran over all of your node modules.

**Comment by sebmck** [comment]
You shouldn't under any circumstance be running webpack over your node modules anyway since it's unnecessary and you'll run into issues like this.

**Comment by roman01la** [comment]
Oh my, thanks :+1:

**Comment by sebmck** [comment]
No problem! Let me know if you run into any other issues. Our [gitter](http://gitter.im/6to5/6to5) room is a better place to ask these kind of questions.
