### ISSUE TITLE
Source maps not working?

### ISSUE THREAD

**Issue by vishnevskiy** [6to5/6to5-loader#26]
I have the following settings on the compiler

```
devtool: 'eval',
```

and the only loader as

```
{test: /\.js$/, exclude: /node_modules|vendor/, loader: ['6to5-loader']},
```

But the source maps are Pointing to files that are post compile with 6to5.

https://www.dropbox.com/s/crqfi0uvh0kstdq/Screenshot%202015-02-02%2013.10.29.png?dl=0

I had this working fine with 6to5ify but I cannot seem to get webpack to work.

(I am running using the dev-server)

**Comment by sebmck** [comment]
Looks like `devtool` has to be set to either `source-map`, `inline-source-map` or `eval-source-map` as per the [docs](https://webpack.github.io/docs/configuration.html#devtool).

**Comment by vishnevskiy** [comment]
That worked for me. Thank you.
