### ISSUE TITLE
Question - how to resolve file paths of modules in node_modules correctly?

### ISSUE THREAD

**Issue by janusch** [6to5/6to5-loader#27]
Hi,
first of all thanks for the great work bringing 6to5 to webpack!
I am still new to both, please bear with me if it is a simple question.

I want to use 6to5-loader to use ES6 modules with webpack.

When i run webpack with the following configuration:

```javascript
module: {
        loaders: [
            { test: /\.js$/, exclude: /node_modules/, loader: '6to5-loader?experimental&optional=selfContained'}
        ]
    }
```
i get the following error:
```bash
Module not found: Error: Cannot resolve module '6to5-runtime/helpers' in /to/js/modules/folder
```

the 6to5-runtime is in the projects local node_modules folder.
How can I adjust the config in a way that the node_modules folder is searched for modules?

i tried addding below lines to the webpack config, without any success:
```javascript
resolveLoader: {
      root: [
        path.join(__dirname, "node_modules")
      ]
}
```

A working solution to the issue or some pointers to the right direction are very appreciated.
Thanks in advance!

Second question, is the ```webpack.ProvidePlugin()``` still the optimal way to define globals, like jQuery, etc for all modules?

**Comment by sebmck** [comment]
Webpack already searches in each `node_modules` folder. It'll check to see if the current directory the file is in has the module available in `node_modules` and if not it goes up the a directory and checks there again. It sounds like you just don't have `6to5-runtime` installed?

**Comment by janusch** [comment]
Thanks for your reply!
I think i figured it out. The thing is that the node_modules folder is in a sibling dir of the scripts folder, and it does not get detected.
When i added:
```javascript
resolve: {
        root: [
            path.join(__dirname, "..", "gulp", "node_modules"),
            path.join(__dirname, "..", "scripts", "modules"),
        ],
        extensions: ['', '.js', '.json'] 
    },
```
to the webpack.config.js it seems to be working now.

Thanks again for putting me on the right path!

**Comment by sebmck** [comment]
@janusch Ah, no problem! Sorry I couldn't have been more help!

**Comment by camsong** [comment]
@janusch @sebmck I had the same problem. 'node_modules' folder is in a sibling dir which is far different folder.
I set `root` path but still did not work. Do you have any ideas about this?

**Comment by camsong** [comment]
Fixed by `resolveLoader. modulesDirectories`
https://github.com/webpack/webpack/issues/1083

**Comment by Couto** [comment]
:+1: :)

**Comment by EdDeAlmeidaJr** [comment]
I've had the same issue and solved it by simply creating a symlink to the correct directory in the directory my `webpack.config.js` is.
